apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2024-05-14T06:49:40Z"
  labels:
    app: spring-petclinic-rest
  name: spring-petclinic-rest
  namespace: default
  resourceVersion: "62726"
  uid: 9a366077-de5f-43cf-a3ee-cc840234c936
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.110.46.138
  clusterIPs:
  - 10.110.46.138
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31799
    port: 9966
    protocol: TCP
    targetPort: 9966
  selector:
    app: spring-petclinic-rest
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
